### ISSUE TITLE
Please upload to Pypi

### ISSUE THREAD

**Issue by epineda** [aaugustin/django-pymssql#3]
I don't know what is the development roadmap, but with the current progress, I can use django-pymssql?

**Comment by aaugustin** [comment]
_Short answer_

Yes, you can. I do. (Of course all the usual caveats of open-source software apply.)

_Long answer_

Before uploading to PyPI, I would like to pass as much of Django's test suite as possible with a released version of pymssql, django-mssql, and Django itself.

For a long time I depended on an unreleased version of pymssql, but that isn't an issue anymore since they made a release in November 2014.

I haven't resumed working on this project because, well, it just works for what I need — calling stored procedures in an existing database.

I'll try to re-run Django's test suite (which takes ages with an SQL Server database in a VM...) and update the list of known failing tests, which is documented in https://github.com/aaugustin/django-pymssql/blob/4e2c7ab77ec85970dece46754631341a53e1a88f/sqlserver_pymssql/base.py#L69-L97.

Even if I don't have time to investigate the test failures, you're right, I should upload to PyPI.

**Comment by aaugustin** [comment]
There you go: https://pypi.python.org/pypi/django-pymssql
